---
- name: Install nginx web server
  tags: nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify:

- name: Creates Root-Website
  file: path=/home/Root/domains/website.com/public_html state=directory owner=www-data group=www-data mode=0775

- name: Upload default index.php for host
  tags: nginx
  copy:
    src: templates/index.php
    dest: /home/Root/domains/website.com/public_html/info.php
    mode: 0644
    owner: www-data
    group: www-data

- name: Upload nginx PHP configuration file
  tags: nginx
  copy:
    src: templates/php.conf
    dest: /etc/nginx

- name: Upload nginx whats host configuration file
  tags: nginx
  copy:
    src: templates/website.conf
    dest: /etc/nginx/sites-available

- name: Create symlink for example host configuration file
  tags: nginx
  file:
    src: /etc/nginx/sites-available/website.conf
    dest: /etc/nginx/sites-enabled/website.conf
    state: link

- name: Remove nginx boilerplate HTML files
  tags: nginx
  file:
    path: /var/www/html
    state: absent

- name: Remove nginx default configuration
  tags: nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
