---
- name: Install PHP-FPM, PHP-APC & fcgiwrap
  tags: php
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php-apc
    - fcgiwrap
    - git
    - vim
    - htop
    - php5-curl
    - wget 
    - python-selinux
    - python3
    - python3-venv
    - unzip


- name: Install PHP packages
  tags: php
  apt: pkg={{ item }} state=present
  with_items:
    - php5-mysql
    - php5-sqlite
    - php5-curl
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-pspell
    - php5-recode
    - php5-snmp
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl

- name: Add tid user
  action: user name=10kthailand password=Mvision@123

- name: Disable potential PHP security risk
  tags: php
  lineinfile:
    dest: /etc/php5/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: 'cgi.fix_pathinfo=0'

- name: Copy php-fpm configuration
  template: src=10kthailand.conf dest=/etc/php5/fpm/pool.d/

- name: Remove www.conf default configuration
  tags: php
  file:
    path: /etc/php5/fpm/pool.d/www.conf
    state: absent

- name: Creates php5 log
  file: path=/var/log/php5/ state=directory owner=www-data group=www-data mode=0775

- name: Remove Apache web server
  tags: php
  apt: pkg={{ item }} state=absent
  with_items:
    - apache2
    - apache2.2-common
    - apache2-doc
    - apache2-mpm-prefork
    - apache2-utils
  notify:
    - start php-fpm
